services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: "-c max_connections=200"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 4s
      retries: 5

  es-cqrs-anatomy:
    build:
      context: .
    container_name: es-cqrs-anatomy
    hostname: host1.com
    depends_on:
      postgres:
        condition: service_healthy

  livebook:
    container_name: livebook
    hostname: host2.com
    image: ghcr.io/livebook-dev/livebook:0.14.3
    ports:
      - 8080:8080
    environment:
      - LIVEBOOK_PASSWORD=es-cqrs-anatomy
    volumes:
      - ./es-cqrs-anatomy.livemd:/data/es-cqrs-anatomy.livemd
    depends_on:
      - es-cqrs-anatomy
